export const cities = [
  // Albany County
  { name: "Albany", slug: "albany-ny" },
  { name: "Cohoes", slug: "cohoes-ny" },
  { name: "Watervliet", slug: "watervliet-ny" },
  { name: "Berne", slug: "berne-ny" },
  { name: "Bethlehem", slug: "bethlehem-ny" },
  { name: "Colonie", slug: "colonie-ny" },
  { name: "Guilderland", slug: "guilderland-ny" },
  { name: "Knox", slug: "knox-ny" },
  { name: "New Scotland", slug: "new-scotland-ny" },
  { name: "Rensselaerville", slug: "rensselaerville-ny" },
  { name: "Westerlo", slug: "westerlo-ny" },
  { name: "Green Island", slug: "green-island-ny" },
  { name: "Menands", slug: "menands-ny" },
  { name: "Voorheesville", slug: "voorheesville-ny" },
  { name: "Delmar", slug: "delmar-ny" },
  { name: "Loudonville", slug: "loudonville-ny" },

  // Rensselaer County
  { name: "Troy", slug: "troy-ny" },
  { name: "Rensselaer", slug: "rensselaer-ny" },
  { name: "Brunswick", slug: "brunswick-ny" },
  { name: "East Greenbush", slug: "east-greenbush-ny" },
  { name: "Hoosick", slug: "hoosick-ny" },
  { name: "Nassau", slug: "nassau-ny" },
  { name: "North Greenbush", slug: "north-greenbush-ny" },
  { name: "Pittstown", slug: "pittstown-ny" },
  { name: "Poestenkill", slug: "poestenkill-ny" },
  { name: "Sand Lake", slug: "sand-lake-ny" },
  { name: "Schodack", slug: "schodack-ny" },
  { name: "Stephentown", slug: "stephentown-ny" },
  { name: "Berlin", slug: "berlin-ny" },
  { name: "Grafton", slug: "grafton-ny" },
  { name: "Valley Falls", slug: "valley-falls-ny" },
  { name: "Castleton-on-Hudson", slug: "castleton-on-hudson-ny" },
  { name: "Hoosick Falls", slug: "hoosick-falls-ny" },
  { name: "Wynantskill", slug: "wynantskill-ny" },

  // Schenectady County
  { name: "Schenectady", slug: "schenectady-ny" },
  { name: "Duanesburg", slug: "duanesburg-ny" },
  { name: "Glenville", slug: "glenville-ny" },
  { name: "Niskayuna", slug: "niskayuna-ny" },
  { name: "Princetown", slug: "princetown-ny" },
  { name: "Rotterdam", slug: "rotterdam-ny" },
  { name: "Scotia", slug: "scotia-ny" },
  { name: "Delanson", slug: "delanson-ny" },

  // Saratoga County
  { name: "Saratoga Springs", slug: "saratoga-springs-ny" },
  { name: "Mechanicville", slug: "mechanicville-ny" },
  { name: "Ballston", slug: "ballston-ny" },
  { name: "Charlton", slug: "charlton-ny" },
  { name: "Clifton Park", slug: "clifton-park-ny" },
  { name: "Corinth", slug: "corinth-ny" },
  { name: "Day", slug: "day-ny" },
  { name: "Edinburg", slug: "edinburg-ny" },
  { name: "Galway", slug: "galway-ny" },
  { name: "Greenfield", slug: "greenfield-ny" },
  { name: "Hadley", slug: "hadley-ny" },
  { name: "Halfmoon", slug: "halfmoon-ny" },
  { name: "Malta", slug: "malta-ny" },
  { name: "Milton", slug: "milton-ny" },
  { name: "Moreau", slug: "moreau-ny" },
  { name: "Providence", slug: "providence-ny" },
  { name: "Wilton", slug: "wilton-ny" },
  { name: "Ballston Spa", slug: "ballston-spa-ny" },
  { name: "Round Lake", slug: "round-lake-ny" },
  { name: "South Glens Falls", slug: "south-glens-falls-ny" },
  { name: "Victory", slug: "victory-ny" },

  // Columbia County
  { name: "Hudson", slug: "hudson-ny" },
  { name: "Ancram", slug: "ancram-ny" },
  { name: "Canaan", slug: "canaan-ny" },
  { name: "Chatham", slug: "chatham-ny" },
  { name: "Claverack", slug: "claverack-ny" },
  { name: "Copake", slug: "copake-ny" },
  { name: "Gallatin", slug: "gallatin-ny" },
  { name: "Ghent", slug: "ghent-ny" },
  { name: "Greenport", slug: "greenport-ny" },
  { name: "Hillsdale", slug: "hillsdale-ny" },
  { name: "Kinderhook", slug: "kinderhook-ny" },
  { name: "Livingston", slug: "livingston-ny" },
  { name: "Stockport", slug: "stockport-ny" },
  { name: "Austerlitz", slug: "austerlitz-ny" },
  { name: "Valatie", slug: "valatie-ny" },
  { name: "Philmont", slug: "philmont-ny" },

  // Greene County
  { name: "Ashland", slug: "ashland-ny" },
  { name: "Athens", slug: "athens-ny" },
  { name: "Cairo", slug: "cairo-ny" },
  { name: "Catskill", slug: "catskill-ny" },
  { name: "Coxsackie", slug: "coxsackie-ny" },
  { name: "Durham", slug: "durham-ny" },
  { name: "Greenville", slug: "greenville-ny" },
  { name: "Hunter", slug: "hunter-ny" },
  { name: "Jewett", slug: "jewett-ny" },
  { name: "Lexington", slug: "lexington-ny" },
  { name: "New Baltimore", slug: "new-baltimore-ny" },
  { name: "Prattsville", slug: "prattsville-ny" },
  { name: "Windham", slug: "windham-ny" },

  // Montgomery County
  { name: "Amsterdam", slug: "amsterdam-ny" },
  { name: "Charleston", slug: "charleston-ny" },
  { name: "Florida", slug: "florida-ny" },
  { name: "Glen", slug: "glen-ny" },
  { name: "Mohawk", slug: "mohawk-ny" },
  { name: "Palatine", slug: "palatine-ny" },

  // Fulton County
  { name: "Gloversville", slug: "gloversville-ny" },
  { name: "Johnstown", slug: "johnstown-ny" },
  { name: "Broadalbin", slug: "broadalbin-ny" },
  { name: "Mayfield", slug: "mayfield-ny" },
  { name: "Northampton", slug: "northampton-ny" },

  // Schoharie County
  { name: "Cobleskill", slug: "cobleskill-ny" },
  { name: "Esperance", slug: "esperance-ny" },
  { name: "Schoharie", slug: "schoharie-ny" },
  { name: "Sharon", slug: "sharon-ny" },
  { name: "Wright", slug: "wright-ny" },

  // Washington County
  { name: "Argyle", slug: "argyle-ny" },
  { name: "Cambridge", slug: "cambridge-ny" },
  { name: "Greenwich", slug: "greenwich-ny" },
  { name: "Jackson", slug: "jackson-ny" },
  { name: "Salem", slug: "salem-ny" },
  { name: "White Creek", slug: "white-creek-ny" },
];
